// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class NewDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_INFO_HERE',
    appId: 'YOUR_INFO_HERE',
    messagingSenderId: 'YOUR_INFO_HERE',
    projectId: 'YOUR_INFO_HERE',
    authDomain: 'YOUR_INFO_HERE',
    storageBucket: 'YOUR_INFO_HERE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_INFO_HERE',
    appId: 'YOUR_INFO_HERE',
    messagingSenderId: 'YOUR_INFO_HERE',
    projectId: 'YOUR_INFO_HERE',
    storageBucket: 'YOUR_INFO_HERE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_INFO_HERE',
    appId: 'YOUR_INFO_HERE',
    messagingSenderId: 'YOUR_INFO_HERE',
    projectId: 'YOUR_INFO_HERE',
    storageBucket: 'YOUR_INFO_HERE',
    iosBundleId: 'YOUR_INFO_HERE',
  );
}
